---
title: "Journal (reproducible report)"
author: "Anurag Rajendraprasad Ananthapuram"
date: "2020-12-06"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Challenge Tidyverse

Last compiled: `r Sys.Date()`

## Sales by location


```{r}
# Data Science at TUHH ------------------------------------------------------
# SALES ANALYSIS ----
cat("\014") #to clear console

# 1.0 Load libraries ----
library(tidyverse)

library(readxl)


# 2.0 Importing Files ----

bikes_tbl      <- read_excel("00_data/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel("00_data/01_bike_sales/01_raw_data/orderlines.xlsx")

#Not required, just for completeness
bikeshops_tbl  <- read_excel("00_data/01_bike_sales/01_raw_data/bikeshops.xlsx")

# 3.0 Examining Data ----
glimpse(bikes_tbl)

glimpse(orderlines_tbl)

glimpse(bikeshops_tbl)

# 4.0 Joining Data ----

bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

bike_orderlines_joined_tbl %>% glimpse()

# 5.0 Wrangling Data ----
bike_orderlines_joined_tbl %>% 
  select(category) %>%
  filter(str_detect(category, "^Mountain")) %>% 
  unique()

bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
  separate(col    = category,
           into   = c("category.1", "category.2", "category.3"),
           sep    = " - ") %>%
  
  mutate(total.price = price * quantity) %>%
  
  select(-...1, -gender) %>%
  
  select(-ends_with(".id")) %>%
  
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,
         everything()) %>%
  
  rename(bikeshop = name) %>%
  
  set_names(names(.) %>% str_replace_all("\\.", "_"))


# 6.1 Sales by location ----

# Step 1 - Manipulate

sales_by_location_tbl <- bike_orderlines_wrangled_tbl %>%
  
  select(location, total_price) %>%
  
separate(col = location,
         into = c("city", "state"),
         sep = ",",
         convert = T) %>%
  
  group_by(state) %>%
  summarize(sales = sum(total_price)) %>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))


# Step 2 - Visualize

sales_by_location_tbl %>%
  
  ggplot(aes(x = state, y = sales)) +
  
  geom_col(fill = "#4caf50",width = .45) +
  
  geom_text(aes(label = sales_text), size = 2,vjust = -1, hjust = 0.5) +
  
  geom_smooth(method = "lm", se = FALSE) +
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  
  expand_limits(y = 2.5e7)+
  
  labs(
    title    = "Revenue by location",
    x = "", 
    y = "Revenue"
  )
```

## Sales by location and year

```{r}
# Data Science at TUHH ------------------------------------------------------
# SALES ANALYSIS ----
cat("\014") #to clear console

# 1.0 Load libraries ----
library(tidyverse)

library(readxl)


# 2.0 Importing Files ----

bikes_tbl      <- read_excel("00_data/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel("00_data/01_bike_sales/01_raw_data/orderlines.xlsx")

#Not required, just for completeness
bikeshops_tbl  <- read_excel("00_data/01_bike_sales/01_raw_data/bikeshops.xlsx")

# 3.0 Examining Data ----
glimpse(bikes_tbl)

glimpse(orderlines_tbl)

glimpse(bikeshops_tbl)

# 4.0 Joining Data ----

bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

bike_orderlines_joined_tbl %>% glimpse()

# 5.0 Wrangling Data ----
bike_orderlines_joined_tbl %>% 
  select(category) %>%
  filter(str_detect(category, "^Mountain")) %>% 
  unique()

bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
  separate(col    = category,
           into   = c("category.1", "category.2", "category.3"),
           sep    = " - ") %>%
  
  mutate(total.price = price * quantity) %>%
  
  select(-...1, -gender) %>%
  
  select(-ends_with(".id")) %>%
  
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,
         everything()) %>%
  
  rename(bikeshop = name) %>%
  
  set_names(names(.) %>% str_replace_all("\\.", "_"))


# 6.1 Sales by location and year  ----

# Step 1 - Manipulate

library(lubridate)
sales_by_year_location_tbl <- bike_orderlines_wrangled_tbl %>%
  
  select(order_date, location, total_price, ) %>%
  
  mutate(year = year(order_date)) %>%
  
  separate(col = location,
           into = c("city", "state"),
           sep = ",",
           convert = T) %>%
  
  group_by(state, year) %>%
  summarize(sales = sum(total_price)) %>%
  ungroup() %>%
  
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

# Step 2 - Visualize

sales_by_year_location_tbl %>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ state) +
  #geom_smooth(method = "lm", se = FALSE)+
  
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and location",
    fill = "Main category" # Changes the legend name
  )
```

# Challenge Data Aquisition

## Indian Premier League (IPL)

```{r}
cat("\014")

# WEBSCRAPING ----

# 1.0 LIBRARIES ----

library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing
library(httr)      #GET() function
library(knitr)

# 1.1 COLLECT PRODUCT FAMILIES ----
url  <- "https://www.iplt20.com/points-table/2020"

# Read in the HTML for the entire webpage
html <- url %>% 
  read_html()


team <- html %>%
  html_nodes(".standings-table__team.standings-table__freeze > a") %>%
  html_text() %>%
  
  stringr::str_extract("(?=)[:alpha:]+.*" ) %>%
  
   enframe(name = "list5", value = "team")

RR <- html %>%
  html_nodes("td") %>%
  html_text() %>%
  enframe(name = "list", value = "Net RR") %>%
  slice(8,20,32,44,56,68,80,92)


position <- html %>%
   html_nodes(".standings-table__freeze.u-text-center") %>%
   html_text() %>%
   enframe(name = "list1", value = "position")

team_url <- html %>%
  html_nodes(".standings-table__freeze > a") %>%
  html_attr('href') %>%
  enframe(name = "list2", value = "subdirectory") %>%
  # Add the domain, because we will get only the subdirectories
  mutate(
    url = glue("https://www.iplt20.com{subdirectory}"))

points <- html %>%
  html_nodes(".js-points") %>%
  html_text() %>%
  as.numeric() %>%
  enframe(name = "list3", value = "points")

played <- html %>%
  html_nodes(".standings-table__padded") %>%
  html_text()%>%
  enframe(name = "list4", value = "played") %>%
  slice(2:9)



data <- html %>%
  html_nodes(".standings-table__optional") %>%
  html_text()

data_1_tbl <- tibble(data) %>%
     slice(7:12)
data_1_row <- as.data.frame(t(data_1_tbl))

data_2_tbl <-  tibble(data) %>%
  slice(15:20)
data_2_row  <- as.data.frame(t(data_2_tbl))

data_3_tbl <-  tibble(data) %>%
  slice(23:28)
data_3_row  <-  as.data.frame(t(data_3_tbl))

data_4_tbl  <-  tibble(data) %>%
  slice(31:36)
data_4_row <-     as.data.frame(t(data_4_tbl))

data_5_tbl <-  tibble(data) %>%
  slice(39:44)
data_5_row <-     as.data.frame(t(data_5_tbl))

data_6_tbl <-  tibble(data) %>%
  slice(47:52)
data_6_row  <-     as.data.frame(t(data_6_tbl))

data_7_tbl <-  tibble(data) %>%
  slice(55:60)
data_7_row  <-     as.data.frame(t(data_7_tbl))

data_8_tbl <-  tibble(data) %>%
  slice(63:68)
data_8_row  <-     as.data.frame(t(data_8_tbl))

full_data <- data_1_row %>%
  bind_rows(data_2_row,data_3_row,data_4_row,data_5_row,data_6_row,data_7_row,data_8_row) %>%
  set_names(c("Won","Lost","Tied","N/R","For","Against"))

points_tbl <- tibble(position,team,played,full_data,RR,points,team_url) %>%
 select(position,team,played,Won,Lost,Tied,'N/R','Net RR',For,Against,points,url)
kable(points_tbl, caption = "IPL 2020 Points Table")
```